name: TemplatePlugin
version: "{{ version }}"
description: "{{ description }}"
# TODO: either this or author
authors: []
main: "org.mythicmc.templateplugin.bukkit.TemplatePlugin"
# TODO: set this as needed api-version: "1.16"
